WITH REVIEW_CNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_REVIEW_CNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING CNT = (SELECT MAX(CNT) FROM REVIEW_CNT)
)

SELECT 
     M.MEMBER_NAME AS MEMBER_NAME,
     R.REVIEW_TEXT AS REVIEW_TEXT,
     DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM MAX_REVIEW_CNT
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;